import { DataSource } from "typeorm";
import { DistrictEntity } from "@lams/shared/database/entities/location/district.entity";

export class DistrictSeeder {
  data: any[] = [
    {
      id: 1,
      division_id: 1,
      division_bbs_code: "10",
      name_en: "BARGUNA",
      name: "বরগুনা",
      bbs_code: "04",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 2,
      division_id: 1,
      division_bbs_code: "10",
      name_en: "BARISAL",
      name: "বরিশাল",
      bbs_code: "06",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 3,
      division_id: 1,
      division_bbs_code: "10",
      name_en: "BHOLA",
      name: "ভোলা",
      bbs_code: "09",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 4,
      division_id: 1,
      division_bbs_code: "10",
      name_en: "JHALOKATI",
      name: "ঝালকাঠি",
      bbs_code: "42",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 5,
      division_id: 1,
      division_bbs_code: "10",
      name_en: "PATUAKHALI",
      name: "পটুয়াখালী",
      bbs_code: "78",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 6,
      division_id: 1,
      division_bbs_code: "10",
      name_en: "PIROJPUR",
      name: "পিরোজপুর",
      bbs_code: "79",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 7,
      division_id: 2,
      division_bbs_code: "20",
      name_en: "BANDARBAN",
      name: "বান্দরবান",
      bbs_code: "03",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 8,
      division_id: 2,
      division_bbs_code: "20",
      name_en: "BRAHMANBARIA",
      name: "ব্রাহ্মণবাড়িয়া",
      bbs_code: "12",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 9,
      division_id: 2,
      division_bbs_code: "20",
      name_en: "CHANDPUR",
      name: "চাঁদপুর",
      bbs_code: "13",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 10,
      division_id: 2,
      division_bbs_code: "20",
      name_en: "CHITTAGONG",
      name: "চট্টগ্রাম",
      bbs_code: "15",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 11,
      division_id: 2,
      division_bbs_code: "20",
      name_en: "COMILLA",
      name: "কুমিল্লা",
      bbs_code: "19",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 12,
      division_id: 2,
      division_bbs_code: "20",
      name_en: "COX'S BAZAR",
      name: "কক্সবাজার ",
      bbs_code: "22",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 13,
      division_id: 2,
      division_bbs_code: "20",
      name_en: "FENI",
      name: "ফেনী",
      bbs_code: "30",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 14,
      division_id: 2,
      division_bbs_code: "20",
      name_en: "KHAGRACHHARI",
      name: "খাগড়াছড়ি",
      bbs_code: "46",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 15,
      division_id: 2,
      division_bbs_code: "20",
      name_en: "LAKSHMIPUR",
      name: "লক্ষ্মীপুর",
      bbs_code: "51",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 16,
      division_id: 2,
      division_bbs_code: "20",
      name_en: "NOAKHALI",
      name: "নোয়াখালী",
      bbs_code: "75",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 17,
      division_id: 2,
      division_bbs_code: "20",
      name_en: "RANGAMATI",
      name: "রাঙ্গামাটি",
      bbs_code: "84",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 18,
      division_id: 3,
      division_bbs_code: "30",
      name_en: "DHAKA",
      name: "ঢাকা ",
      bbs_code: "26",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 19,
      division_id: 3,
      division_bbs_code: "30",
      name_en: "FARIDPUR",
      name: "ফরিদপুর",
      bbs_code: "29",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 20,
      division_id: 3,
      division_bbs_code: "30",
      name_en: "GAZIPUR",
      name: "গাজীপুর ",
      bbs_code: "33",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 21,
      division_id: 3,
      division_bbs_code: "30",
      name_en: "GOPALGANJ",
      name: "গোপালগঞ্জ",
      bbs_code: "35",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 22,
      division_id: 8,
      division_bbs_code: "45",
      name_en: "JAMALPUR",
      name: "জামালপুর ",
      bbs_code: "39",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 14:08:46",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 23,
      division_id: 3,
      division_bbs_code: "30",
      name_en: "KISHOREGONJ",
      name: "কিশোরগঞ্জ ",
      bbs_code: "48",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 24,
      division_id: 3,
      division_bbs_code: "30",
      name_en: "MADARIPUR",
      name: "মাদারীপুর",
      bbs_code: "54",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 25,
      division_id: 3,
      division_bbs_code: "30",
      name_en: "MANIKGANJ",
      name: "মানিকগঞ্জ",
      bbs_code: "56",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 26,
      division_id: 3,
      division_bbs_code: "30",
      name_en: "MUNSHIGANJ",
      name: "মুন্সিগঞ্জ",
      bbs_code: "59",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 27,
      division_id: 8,
      division_bbs_code: "45",
      name_en: "MYMENSINGH",
      name: "ময়মনসিংহ",
      bbs_code: "61",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 19:32:20",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 28,
      division_id: 3,
      division_bbs_code: "30",
      name_en: "NARAYANGANJ",
      name: "নারায়ণগঞ্জ",
      bbs_code: "67",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 29,
      division_id: 3,
      division_bbs_code: "30",
      name_en: "NARSINGDI",
      name: "নরসিংদী",
      bbs_code: "68",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 30,
      division_id: 8,
      division_bbs_code: "45",
      name_en: "NETRAKONA",
      name: "নেত্রকোণা",
      bbs_code: "72",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 19:31:29",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 31,
      division_id: 3,
      division_bbs_code: "30",
      name_en: "RAJBARI",
      name: "রাজবাড়ী",
      bbs_code: "82",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 32,
      division_id: 3,
      division_bbs_code: "30",
      name_en: "SHARIATPUR",
      name: "শরীয়তপুর",
      bbs_code: "86",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 33,
      division_id: 8,
      division_bbs_code: "45",
      name_en: "SHERPUR",
      name: "শেরপুর",
      bbs_code: "89",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 19:31:55",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 34,
      division_id: 3,
      division_bbs_code: "30",
      name_en: "TANGAIL",
      name: "টাঙ্গাইল",
      bbs_code: "93",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 35,
      division_id: 4,
      division_bbs_code: "40",
      name_en: "BAGERHAT",
      name: "বাগেরহাট",
      bbs_code: "01",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 36,
      division_id: 4,
      division_bbs_code: "40",
      name_en: "CHUADANGA",
      name: "চুয়াডাঙ্গা ",
      bbs_code: "18",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 37,
      division_id: 4,
      division_bbs_code: "40",
      name_en: "JESSORE",
      name: "যশোর",
      bbs_code: "41",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 38,
      division_id: 4,
      division_bbs_code: "40",
      name_en: "JHENAIDAH",
      name: "ঝিনাইদহ",
      bbs_code: "44",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 39,
      division_id: 4,
      division_bbs_code: "40",
      name_en: "KHULNA",
      name: "খুলনা",
      bbs_code: "47",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 40,
      division_id: 4,
      division_bbs_code: "40",
      name_en: "KUSHTIA",
      name: "কুষ্টিয়া",
      bbs_code: "50",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 41,
      division_id: 4,
      division_bbs_code: "40",
      name_en: "MAGURA",
      name: "মাগুরা",
      bbs_code: "55",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 42,
      division_id: 4,
      division_bbs_code: "40",
      name_en: "MEHERPUR",
      name: "মেহেরপুর ",
      bbs_code: "57",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 43,
      division_id: 4,
      division_bbs_code: "40",
      name_en: "NARAIL",
      name: "নড়াইল",
      bbs_code: "65",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 44,
      division_id: 4,
      division_bbs_code: "40",
      name_en: "SATKHIRA",
      name: "সাতক্ষীরা",
      bbs_code: "87",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 45,
      division_id: 5,
      division_bbs_code: "50",
      name_en: "BOGRA",
      name: "বগুড়া ",
      bbs_code: "10",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 46,
      division_id: 5,
      division_bbs_code: "50",
      name_en: "JOYPURHAT",
      name: "জয়পুরহাট",
      bbs_code: "38",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 47,
      division_id: 5,
      division_bbs_code: "50",
      name_en: "NAOGAON",
      name: "নওগাঁ",
      bbs_code: "64",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 48,
      division_id: 5,
      division_bbs_code: "50",
      name_en: "NATORE",
      name: "নাটোর",
      bbs_code: "69",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 49,
      division_id: 5,
      division_bbs_code: "50",
      name_en: "CHAPAI NABABGANJ",
      name: "চাঁপাইনবাবগঞ্জ",
      bbs_code: "70",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 50,
      division_id: 5,
      division_bbs_code: "50",
      name_en: "PABNA",
      name: "পাবনা",
      bbs_code: "76",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 51,
      division_id: 5,
      division_bbs_code: "50",
      name_en: "RAJSHAHI",
      name: "রাজশাহী",
      bbs_code: "81",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 52,
      division_id: 5,
      division_bbs_code: "50",
      name_en: "SIRAJGANJ",
      name: "সিরাজগঞ্জ",
      bbs_code: "88",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 53,
      division_id: 6,
      division_bbs_code: "55",
      name_en: "DINAJPUR",
      name: "দিনাজপুর",
      bbs_code: "27",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 54,
      division_id: 6,
      division_bbs_code: "55",
      name_en: "GAIBANDHA",
      name: "গাইবান্ধা ",
      bbs_code: "32",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 55,
      division_id: 6,
      division_bbs_code: "55",
      name_en: "KURIGRAM",
      name: "কুড়িগ্রাম ",
      bbs_code: "49",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 56,
      division_id: 6,
      division_bbs_code: "55",
      name_en: "LALMONIRHAT",
      name: "লালমনিরহাট",
      bbs_code: "52",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 57,
      division_id: 6,
      division_bbs_code: "55",
      name_en: "NILPHAMARI",
      name: "নীলফামারী",
      bbs_code: "73",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 58,
      division_id: 6,
      division_bbs_code: "55",
      name_en: "PANCHAGARH",
      name: "পঞ্চগড়",
      bbs_code: "77",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 59,
      division_id: 6,
      division_bbs_code: "55",
      name_en: "RANGPUR",
      name: "রংপুর",
      bbs_code: "85",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 60,
      division_id: 6,
      division_bbs_code: "55",
      name_en: "THAKURGAON",
      name: "ঠাকুরগাঁও",
      bbs_code: "94",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 61,
      division_id: 7,
      division_bbs_code: "60",
      name_en: "HABIGANJ",
      name: "হবিগঞ্জ",
      bbs_code: "36",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 62,
      division_id: 7,
      division_bbs_code: "60",
      name_en: "MAULVIBAZAR",
      name: "মৌলভীবাজার",
      bbs_code: "58",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 63,
      division_id: 7,
      division_bbs_code: "60",
      name_en: "SUNAMGANJ",
      name: "সুনামগঞ্জ",
      bbs_code: "90",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
    {
      id: 64,
      division_id: 7,
      division_bbs_code: "60",
      name_en: "SYLHET",
      name: "সিলেট",
      bbs_code: "91",
      row_status: 1,
      created_at: "2024-04-02 13:39:00",
      updated_at: "2024-04-02 13:39:00",
      deleted_at: null,
      created_by: null,
      updated_by: null,
      deleted_by: null,
    },
  ];

  async run(dataSource: DataSource): Promise<any> {
    await dataSource.query("SET FOREIGN_KEY_CHECKS=0");
    await dataSource.getRepository(DistrictEntity).clear();
    await dataSource.manager.save(DistrictEntity, this.data);
    await dataSource.query("SET FOREIGN_KEY_CHECKS=1");
  }
}
