version: '3.8'

services:
  master:
    image: mysql:8.0
    container_name: mysql-master
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecommerce
      MYSQL_REPLICATION_USER: repl_user
      MYSQL_REPLICATION_PASSWORD: repl_password
    ports:
      - "3306:3306"
    volumes:
      - master_data:/var/lib/mysql
      - ./mysql/master.cnf:/etc/mysql/conf.d/master.cnf
    command: ['mysqld']

  replica1:
    image: mysql:8.0
    container_name: mysql-replica1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecommerce
      MYSQL_REPLICATION_USER: repl_user
      MYSQL_REPLICATION_PASSWORD: repl_password
    ports:
      - "3307:3306"
    volumes:
      - replica1_data:/var/lib/mysql
      - ./mysql/replica.cnf:/etc/mysql/conf.d/replica.cnf
    depends_on:
      - master

  replica2:
    image: mysql:8.0
    container_name: mysql-replica2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecommerce
      MYSQL_REPLICATION_USER: repl_user
      MYSQL_REPLICATION_PASSWORD: repl_password
    ports:
      - "3308:3306"
    volumes:
      - replica2_data:/var/lib/mysql
      - ./mysql/replica.cnf:/etc/mysql/conf.d/replica.cnf
    depends_on:
      - master

  replica3:
    image: mysql:8.0
    container_name: mysql-replica3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecommerce
      MYSQL_REPLICATION_USER: repl_user
      MYSQL_REPLICATION_PASSWORD: repl_password
    ports:
      - "3309:3306"
    volumes:
      - replica3_data:/var/lib/mysql
      - ./mysql/replica.cnf:/etc/mysql/conf.d/replica.cnf
    depends_on:
      - master
volumes:
  master_data:
  replica1_data:
  replica2_data:
  replica3_data:
