import { DataSource } from "typeorm";
import { PermissionEntity } from "@lams/shared/database/entities/user/permission.entity";
import { Permissions } from "@lams/shared/utils/util/permissions";

export class PermissionSeeder {
  data: any[] = [
    {
      id: 1,
      name: "MANAGE_USER",
      name_en: "MANAGE_USER",
      permission_key: Permissions.MANAGE_USER,
      permission_module_id: 1,
    },
    {
      id: 2,
      name: "MANAGE_USER_TRAINING",
      name_en: "MANAGE_USER_TRAINING",
      permission_key: Permissions.MANAGE_USER_TRAINING,
      permission_module_id: 1,
    },
    {
      id: 3,
      name: "MANAGE_PERMISSION_MODULE",
      name_en: "MANAGE_PERMISSION_MODULE",
      permission_key: Permissions.MANAGE_PERMISSION_MODULE,
      permission_module_id: 1,
    },
    {
      id: 4,
      name: "MANAGE_PERMISSION_GROUP",
      name_en: "MANAGE_PERMISSION_GROUP",
      permission_key: Permissions.MANAGE_PERMISSION_GROUP,
      permission_module_id: 1,
    },
    {
      id: 5,
      name: "MANAGE_PERMISSIONS",
      name_en: "MANAGE_PERMISSIONS",
      permission_key: Permissions.MANAGE_PERMISSIONS,
      permission_module_id: 1,
    },
    {
      id: 6,
      name: "VIEW_ALL_USER_REPORT",
      name_en: "VIEW_ALL_USER_REPORT",
      permission_key: Permissions.VIEW_ALL_USER_REPORT,
      permission_module_id: 2,
    },
    {
      id: 7,
      name: "VIEW_ALL_ATTENDANCE",
      name_en: "VIEW_ALL_ATTENDANCE",
      permission_key: Permissions.VIEW_ALL_ATTENDANCE,
      permission_module_id: 3,
    },
    {
      id: 8,
      name: "VIEW_ALL_EMPLOYEES_ATTENDANCE",
      name_en: "VIEW_ALL_EMPLOYEES_ATTENDANCE",
      permission_key: Permissions.VIEW_ALL_EMPLOYEES_ATTENDANCE,
      permission_module_id: 3,
    },
    {
      id: 9,
      name: "UPLOAD_ATTENDANCE",
      name_en: "UPLOAD_ATTENDANCE",
      permission_key: Permissions.UPLOAD_ATTENDANCE,
      permission_module_id: 3,
    },
    {
      id: 10,
      name: "MANAGE_SITE_VISIT",
      name_en: "MANAGE_SITE_VISIT",
      permission_key: Permissions.MANAGE_SITE_VISIT,
      permission_module_id: 4,
    },
    {
      id: 11,
      name: "VIEW_ALL_EMPLOYEES_SITE_VISIT",
      name_en: "VIEW_ALL_EMPLOYEES_SITE_VISIT",
      permission_key: Permissions.VIEW_ALL_EMPLOYEES_SITE_VISIT,
      permission_module_id: 4,
    },
    {
      id: 12,
      name: "MANAGE_GEO_LOCATION",
      name_en: "MANAGE_GEO_LOCATION",
      permission_key: Permissions.MANAGE_GEO_LOCATION,
      permission_module_id: 5,
    },
    {
      id: 13,
      name: "MANAGE_OFFICE_LAYER",
      name_en: "MANAGE_OFFICE_LAYER",
      permission_key: Permissions.MANAGE_OFFICE_LAYER,
      permission_module_id: 6,
    },
    {
      id: 14,
      name: "MANAGE_MINISTRY_OFFICE",
      name_en: "MANAGE_MINISTRY_OFFICE",
      permission_key: Permissions.MANAGE_MINISTRY_OFFICE,
      permission_module_id: 6,
    },
    {
      id: 15,
      name: "MANAGE_BASE_OFFICE",
      name_en: "MANAGE_BASE_OFFICE",
      permission_key: Permissions.MANAGE_BASE_OFFICE,
      permission_module_id: 6,
    },
    {
      id: 16,
      name: "MANAGE_BASE_OFFICE_ORGANOGRAM",
      name_en: "MANAGE_BASE_OFFICE_ORGANOGRAM",
      permission_key: Permissions.MANAGE_BASE_OFFICE_ORGANOGRAM,
      permission_module_id: 6,
    },
    {
      id: 17,
      name: "MANAGE_OFFICE",
      name_en: "MANAGE_OFFICE",
      permission_key: Permissions.MANAGE_OFFICE,
      permission_module_id: 6,
    },
    {
      id: 18,
      name: "MANAGE_OFFICE_ORGANOGRAM",
      name_en: "MANAGE_OFFICE_ORGANOGRAM",
      permission_key: Permissions.MANAGE_OFFICE_ORGANOGRAM,
      permission_module_id: 6,
    },
    {
      id: 19,
      name: "MANAGE_OFFICE_ORGANOGRAM_USER",
      name_en: "MANAGE_OFFICE_ORGANOGRAM_USER",
      permission_key: Permissions.MANAGE_OFFICE_ORGANOGRAM_USER,
      permission_module_id: 6,
    },
    {
      id: 20,
      name: "MANAGE_OFFICE_ORGANOGRAM_PERMISSION",
      name_en: "MANAGE_OFFICE_ORGANOGRAM_PERMISSION",
      permission_key: Permissions.MANAGE_OFFICE_ORGANOGRAM_PERMISSION,
      permission_module_id: 6,
    },
    {
      id: 21,
      name: "MANAGE_RANK",
      name_en: "MANAGE_RANK",
      permission_key: Permissions.MANAGE_RANK,
      permission_module_id: 6,
    },
    {
      id: 22,
      name: "MANAGE_GRADE",
      name_en: "MANAGE_GRADE",
      permission_key: Permissions.MANAGE_GRADE,
      permission_module_id: 6,
    },
    {
      id: 23,
      name: "VIEW_ALL_NOTICE",
      name_en: "VIEW_ALL_NOTICE",
      permission_key: Permissions.VIEW_ALL_NOTICE,
      permission_module_id: 7,
    },
    {
      id: 24,
      name: "CREATE_NOTICE",
      name_en: "CREATE_NOTICE",
      permission_key: Permissions.CREATE_NOTICE,
      permission_module_id: 7,
    },
    {
      id: 25,
      name: "APPROVE_NOTICE",
      name_en: "APPROVE_NOTICE",
      permission_key: Permissions.APPROVE_NOTICE,
      permission_module_id: 7,
    },
    {
      id: 26,
      name: "MANAGE_OFFICE_TIME",
      name_en: "MANAGE_OFFICE_TIME",
      permission_key: Permissions.MANAGE_OFFICE_TIME,
      permission_module_id: 8,
    },
    {
      id: 27,
      name: "MANAGE_CALENDER",
      name_en: "MANAGE_CALENDER",
      permission_key: Permissions.MANAGE_CALENDER,
      permission_module_id: 8,
    },
    {
      id: 28,
      name: "MANAGE_WORK_FLOW",
      name_en: "MANAGE_WORK_FLOW",
      permission_key: Permissions.MANAGE_WORK_FLOW,
      permission_module_id: 8,
    },
    {
      id: 29,
      name: "CREATE_AUDIT_INSPECTION",
      name_en: "CREATE_AUDIT_INSPECTION",
      permission_key: Permissions.CREATE_AUDIT_INSPECTION,
      permission_module_id: 9,
    },
    {
      id: 30,
      name: "APPROVE_AUDIT_INSPECTION",
      name_en: "APPROVE_AUDIT_INSPECTION",
      permission_key: Permissions.APPROVE_AUDIT_INSPECTION,
      permission_module_id: 9,
    },
    {
      id: 31,
      name: "MANAGE_AUDIT_INSPECTION_FILE_TYPE",
      name_en: "MANAGE_AUDIT_INSPECTION_FILE_TYPE",
      permission_key: Permissions.MANAGE_AUDIT_INSPECTION_FILE_TYPE,
      permission_module_id: 9,
    },
    {
      id: 32,
      name: "MANAGE_AUDIT_INSPECTION_DISPOSAL_TYPE",
      name_en: "MANAGE_AUDIT_INSPECTION_DISPOSAL_TYPE",
      permission_key: Permissions.MANAGE_AUDIT_INSPECTION_DISPOSAL_TYPE,
      permission_module_id: 9,
    },
    {
      id: 33,
      name: "MANAGE_CATEGORY",
      name_en: "MANAGE_CATEGORY",
      permission_key: Permissions.MANAGE_CATEGORY,
      permission_module_id: 10,
    },
    {
      id: 34,
      name: "MANAGE_SUB_CATEGORY",
      name_en: "MANAGE_SUB_CATEGORY",
      permission_key: Permissions.MANAGE_SUB_CATEGORY,
      permission_module_id: 10,
    },
    {
      id: 35,
      name: "MANAGE_ASSET",
      name_en: "MANAGE_ASSET",
      permission_key: Permissions.MANAGE_ASSET,
      permission_module_id: 10,
    },
    {
      id: 36,
      name: "MANAGE_INVENTORY",
      name_en: "MANAGE_INVENTORY",
      permission_key: Permissions.MANAGE_INVENTORY,
      permission_module_id: 10,
    },
    {
      id: 37,
      name: "MANAGE_ASSET_INVENTORY_ITEM",
      name_en: "MANAGE_ASSET_INVENTORY_ITEM",
      permission_key: Permissions.MANAGE_ASSET_INVENTORY_ITEM,
      permission_module_id: 10,
    },
    {
      id: 38,
      name: "VIEW_ALL_ASSET_REQUISITION",
      name_en: "VIEW_ALL_ASSET_REQUISITION",
      permission_key: Permissions.VIEW_ALL_ASSET_REQUISITION,
      permission_module_id: 10,
    },
    {
      id: 39,
      name: "APPROVE_ASSET_REQUISITION",
      name_en: "APPROVE_ASSET_REQUISITION",
      permission_key: Permissions.APPROVE_ASSET_REQUISITION,
      permission_module_id: 10,
    },
    {
      id: 40,
      name: "CREATE_APPRAISAL",
      name_en: "CREATE_APPRAISAL",
      permission_key: Permissions.CREATE_APPRAISAL,
      permission_module_id: 11,
    },
    {
      id: 41,
      name: "APPROVE_APPRAISAL",
      name_en: "APPROVE_APPRAISAL",
      permission_key: Permissions.APPROVE_APPRAISAL,
      permission_module_id: 11,
    },
    {
      id: 42,
      name: "CREATE_TRANSFER",
      name_en: "CREATE_TRANSFER",
      permission_key: Permissions.CREATE_TRANSFER,
      permission_module_id: 12,
    },
    {
      id: 43,
      name: "APPROVE_TRANSFER",
      name_en: "APPROVE_TRANSFER",
      permission_key: Permissions.APPROVE_TRANSFER,
      permission_module_id: 12,
    },
    {
      id: 44,
      name: "GENERATE_TRANSFER_LETTER",
      name_en: "GENERATE_TRANSFER_LETTER",
      permission_key: Permissions.GENERATE_TRANSFER_LETTER,
      permission_module_id: 12,
    },
    {
      id: 45,
      name: "GENERATE_RELEASE_LETTER",
      name_en: "GENERATE_RELEASE_LETTER",
      permission_key: Permissions.GENERATE_RELEASE_LETTER,
      permission_module_id: 12,
    },
    {
      id: 46,
      name: "OFFICE_ORDER_TRANSFER",
      name_en: "OFFICE_ORDER_TRANSFER",
      permission_key: Permissions.OFFICE_ORDER_TRANSFER,
      permission_module_id: 12,
    },
    {
      id: 47,
      name: "MANAGE_LEAVE_CATEGORY",
      name_en: "MANAGE_LEAVE_CATEGORY",
      permission_key: Permissions.MANAGE_LEAVE_CATEGORY,
      permission_module_id: 13,
    },
    {
      id: 48,
      name: "MANAGE_LEAVE_TYPE",
      name_en: "MANAGE_LEAVE_TYPE",
      permission_key: Permissions.MANAGE_LEAVE_TYPE,
      permission_module_id: 13,
    },
    {
      id: 49,
      name: "MANAGE_LEAVE_RULE",
      name_en: "MANAGE_LEAVE_RULE",
      permission_key: Permissions.MANAGE_LEAVE_RULE,
      permission_module_id: 13,
    },
    {
      id: 50,
      name: "MANAGE_LEAVE_PLACEHOLDER",
      name_en: "MANAGE_LEAVE_PLACEHOLDER",
      permission_key: Permissions.MANAGE_LEAVE_PLACEHOLDER,
      permission_module_id: 13,
    },
    {
      id: 51,
      name: "CREATE_LEAVE_APPLICATION",
      name_en: "CREATE_LEAVE_APPLICATION",
      permission_key: Permissions.CREATE_LEAVE_APPLICATION,
      permission_module_id: 13,
    },
    {
      id: 52,
      name: "APPROVE_LEAVE_APPLICATION",
      name_en: "APPROVE_LEAVE_APPLICATION",
      permission_key: Permissions.APPROVE_LEAVE_APPLICATION,
      permission_module_id: 13,
    },
    {
      id: 53,
      name: "MANAGE_AWARD",
      name_en: "MANAGE_AWARD",
      permission_key: Permissions.MANAGE_AWARD,
      permission_module_id: 14,
    },
    {
      id: 54,
      name: "ASSIGN_AWARD",
      name_en: "ASSIGN_AWARD",
      permission_key: Permissions.ASSIGN_AWARD,
      permission_module_id: 14,
    },
    {
      id: 55,
      name: "MANAGE_AWARD_QUESTION",
      name_en: "MANAGE_AWARD_QUESTION",
      permission_key: Permissions.MANAGE_AWARD_QUESTION,
      permission_module_id: 14,
    },
    {
      id: 56,
      name: "CREATE_AWARD_SCORE",
      name_en: "CREATE_AWARD_SCORE",
      permission_key: Permissions.CREATE_AWARD_SCORE,
      permission_module_id: 14,
    },
    {
      id: 57,
      name: "CREATE_AWARD_RECOMMENDATION",
      name_en: "CREATE_AWARD_RECOMMENDATION",
      permission_key: Permissions.CREATE_AWARD_RECOMMENDATION,
      permission_module_id: 14,
    },
    {
      id: 58,
      name: "VIEW_DISCIPLINARY_ACTION",
      name_en: "VIEW_DISCIPLINARY_ACTION",
      permission_key: Permissions.VIEW_DISCIPLINARY_ACTION,
      permission_module_id: 15,
    },
    {
      id: 59,
      name: "CREATE_DISCIPLINARY_ACTION",
      name_en: "CREATE_DISCIPLINARY_ACTION",
      permission_key: Permissions.CREATE_DISCIPLINARY_ACTION,
      permission_module_id: 15,
    },
    {
      id: 60,
      name: "MANAGE_LOAN_TYPE",
      name_en: "MANAGE_LOAN_TYPE",
      permission_key: Permissions.MANAGE_LOAN_TYPE,
      permission_module_id: 16,
    },
    {
      id: 61,
      name: "MANAGE_LOAN_INFORMATION",
      name_en: "MANAGE_LOAN_INFORMATION",
      permission_key: Permissions.MANAGE_LOAN_INFORMATION,
      permission_module_id: 16,
    },
    {
      id: 62,
      name: "VIEW_ALL_ACQUISITION",
      name_en: "VIEW_ALL_ACQUISITION",
      permission_key: Permissions.VIEW_ALL_ACQUISITION,
      permission_module_id: 17,
    },
    {
      id: 63,
      name: "MANAGE_ACQUISITION",
      name_en: "MANAGE_ACQUISITION",
      permission_key: Permissions.MANAGE_ACQUISITION,
      permission_module_id: 17,
    },
    {
      id: 64,
      name: "VIEW_ALL_JAL_MAHAL",
      name_en: "VIEW_ALL_JAL_MAHAL",
      permission_key: Permissions.VIEW_ALL_JAL_MAHAL,
      permission_module_id: 17,
    },
    {
      id: 65,
      name: "MANAGE_JAL_MAHAL",
      name_en: "MANAGE_JAL_MAHAL",
      permission_key: Permissions.MANAGE_JAL_MAHAL,
      permission_module_id: 17,
    },
    {
      id: 66,
      name: "VIEW_ALL_BALU_MAHAL",
      name_en: "VIEW_ALL_BALU_MAHAL",
      permission_key: Permissions.VIEW_ALL_BALU_MAHAL,
      permission_module_id: 17,
    },
    {
      id: 67,
      name: "MANAGE_BALU_MAHAL",
      name_en: "MANAGE_BALU_MAHAL",
      permission_key: Permissions.MANAGE_BALU_MAHAL,
      permission_module_id: 17,
    },
    {
      id: 68,
      name: "VIEW_ALL_LOBON_MAHAL",
      name_en: "VIEW_ALL_LOBON_MAHAL",
      permission_key: Permissions.VIEW_ALL_LOBON_MAHAL,
      permission_module_id: 17,
    },
    {
      id: 69,
      name: "MANAGE_LOBON_MAHAL",
      name_en: "MANAGE_LOBON_MAHAL",
      permission_key: Permissions.MANAGE_LOBON_MAHAL,
      permission_module_id: 17,
    },
    {
      id: 70,
      name: "VIEW_ALL_CHINGRI_MAHAL",
      name_en: "VIEW_ALL_CHINGRI_MAHAL",
      permission_key: Permissions.VIEW_ALL_CHINGRI_MAHAL,
      permission_module_id: 17,
    },
    {
      id: 71,
      name: "MANAGE_CHINGRI_MAHAL",
      name_en: "MANAGE_CHINGRI_MAHAL",
      permission_key: Permissions.MANAGE_CHINGRI_MAHAL,
      permission_module_id: 17,
    },
    {
      id: 72,
      name: "VIEW_ALL_BASH_MAHAL",
      name_en: "VIEW_ALL_BASH_MAHAL",
      permission_key: Permissions.VIEW_ALL_BASH_MAHAL,
      permission_module_id: 17,
    },
    {
      id: 73,
      name: "MANAGE_BASH_MAHAL",
      name_en: "MANAGE_BASH_MAHAL",
      permission_key: Permissions.MANAGE_BASH_MAHAL,
      permission_module_id: 17,
    },
    {
      id: 74,
      name: "VIEW_ALL_KHASJOMI",
      name_en: "VIEW_ALL_KHASJOMI",
      permission_key: Permissions.VIEW_ALL_KHASJOMI,
      permission_module_id: 17,
    },
    {
      id: 75,
      name: "MANAGE_KHASJOMI",
      name_en: "MANAGE_KHASJOMI",
      permission_key: Permissions.MANAGE_KHASJOMI,
      permission_module_id: 17,
    },
    {
      id: 76,
      name: "VIEW_ALL_HATBAZAR",
      name_en: "VIEW_ALL_HATBAZAR",
      permission_key: Permissions.VIEW_ALL_HATBAZAR,
      permission_module_id: 17,
    },
    {
      id: 77,
      name: "MANAGE_HATBAZAR",
      name_en: "MANAGE_HATBAZAR",
      permission_key: Permissions.MANAGE_HATBAZAR,
      permission_module_id: 17,
    },
    {
      id: 78,
      name: "VIEW_ALL_ABANDONED_PROPERTY",
      name_en: "VIEW_ALL_ABANDONED_PROPERTY",
      permission_key: Permissions.VIEW_ALL_ABANDONED_PROPERTY,
      permission_module_id: 17,
    },
    {
      id: 79,
      name: "MANAGE_ABANDONED_PROPERTY",
      name_en: "MANAGE_ABANDONED_PROPERTY",
      permission_key: Permissions.MANAGE_ABANDONED_PROPERTY,
      permission_module_id: 17,
    },
    {
      id: 80,
      name: "VIEW_ALL_CHA_BAGAN",
      name_en: "VIEW_ALL_CHA_BAGAN",
      permission_key: Permissions.VIEW_ALL_CHA_BAGAN,
      permission_module_id: 17,
    },
    {
      id: 81,
      name: "MANAGE_CHA_BAGAN",
      name_en: "MANAGE_CHA_BAGAN",
      permission_key: Permissions.MANAGE_CHA_BAGAN,
      permission_module_id: 17,
    },
    {
      id: 82,
      name: "MANAGE_PROSPECTIVE_REAL_ESTATE_DATA",
      name_en: "MANAGE_PROSPECTIVE_REAL_ESTATE_DATA",
      permission_key: Permissions.MANAGE_PROSPECTIVE_REAL_ESTATE_DATA,
      permission_module_id: 18,
    },
    {
      id: 83,
      name: "VIEW_PROSPECTIVE_REAL_ESTATE_DATA",
      name_en: "VIEW_PROSPECTIVE_REAL_ESTATE_DATA",
      permission_key: Permissions.VIEW_PROSPECTIVE_REAL_ESTATE_DATA,
      permission_module_id: 18,
    },
    {
      id: 84,
      name: "MANAGE_EXPECTING_AGENCY",
      name_en: "MANAGE_EXPECTING_AGENCY",
      permission_key: Permissions.MANAGE_EXPECTING_AGENCY,
      permission_module_id: 19,
    },
    {
      id: 85,
      name: "VIEW_ALL_EXPECTING_AGENCY",
      name_en: "VIEW_ALL_EXPECTING_AGENCY",
      permission_key: Permissions.VIEW_ALL_EXPECTING_AGENCY,
      permission_module_id: 19,
    },
    {
      id: 86,
      name: "VIEW_ALL_PERSONAL_COMMENT",
      name_en: "VIEW_ALL_PERSONAL_COMMENT",
      permission_key: Permissions.VIEW_ALL_PERSONAL_COMMENT,
      permission_module_id: 20,
    },
    {
      id: 87,
      name: "VIEW_ALL_GIVEN_COMMENT",
      name_en: "VIEW_ALL_GIVEN_COMMENT",
      permission_key: Permissions.VIEW_ALL_GIVEN_COMMENT,
      permission_module_id: 20,
    },
    {
      id: 88,
      name: "CREATE_GIVEN_COMMENT",
      name_en: "CREATE_GIVEN_COMMENT",
      permission_key: Permissions.CREATE_GIVEN_COMMENT,
      permission_module_id: 20,
    },
    {
      id: 89,
      name: "VIEW_SINGLE_GIVEN_COMMENT",
      name_en: "VIEW_SINGLE_GIVEN_COMMENT",
      permission_key: Permissions.VIEW_SINGLE_GIVEN_COMMENT,
      permission_module_id: 20,
    },
    {
      id: 90,
      name: "MANAGE_COMMENT_TOPIC",
      name_en: "MANAGE_COMMENT_TOPIC",
      permission_key: Permissions.MANAGE_COMMENT_TOPIC,
      permission_module_id: 20,
    },
    {
      id: 91,
      name: "VIEW_ALL_MY_MEMORY",
      name_en: "VIEW_ALL_MY_MEMORY",
      permission_key: Permissions.VIEW_ALL_MY_MEMORY,
      permission_module_id: 21,
    },
    {
      id: 92,
      name: "VIEW_ALL_ACCESSOR_MEMORY",
      name_en: "VIEW_ALL_ACCESSOR_MEMORY",
      permission_key: Permissions.VIEW_ALL_ACCESSOR_MEMORY,
      permission_module_id: 21,
    },
    {
      id: 93,
      name: "VIEW_ALL_VACANT_POST",
      name_en: "VIEW_ALL_VACANT_POST",
      permission_key: Permissions.VIEW_ALL_VACANT_POST,
      permission_module_id: 22,
    },
    {
      id: 94,
      name: "VIEW_ALL_RECRUITMENT",
      name_en: "VIEW_ALL_RECRUITMENT",
      permission_key: Permissions.VIEW_ALL_RECRUITMENT,
      permission_module_id: 22,
    },
    {
      id: 95,
      name: "FULL_BOARD_HEARING",
      name_en: "FULL_BOARD_HEARING",
      permission_key: Permissions.FULL_BOARD_HEARING,
      permission_module_id: 23,
    },
    {
      id: 96,
      name: "CHAIRMAN_BOARD_HEARING",
      name_en: "CHAIRMAN_BOARD_HEARING",
      permission_key: Permissions.CHAIRMAN_BOARD_HEARING,
      permission_module_id: 23,
    },
    {
      id: 97,
      name: "MEMBER_1_BOARD_HEARING",
      name_en: "MEMBER_1_BOARD_HEARING",
      permission_key: Permissions.MEMBER_1_BOARD_HEARING,
      permission_module_id: 23,
    },
    {
      id: 98,
      name: "MEMBER_2_BOARD_HEARING",
      name_en: "MEMBER_2_BOARD_HEARING",
      permission_key: Permissions.MEMBER_2_BOARD_HEARING,
      permission_module_id: 23,
    },
    {
      id: 99,
      name: "VIEW_ALL_ONLINE_HEARING",
      name_en: "VIEW_ALL_ONLINE_HEARING",
      permission_key: Permissions.VIEW_ALL_ONLINE_HEARING,
      permission_module_id: 23,
    },
    {
      id: 100,
      name: "MANAGE_SERVICE",
      name_en: "MANAGE_SERVICE",
      permission_key: Permissions.MANAGE_SERVICE,
      permission_module_id: 24,
    },
    {
      id: 101,
      name: "MANAGE_NOTIFICATION",
      name_en: "MANAGE_NOTIFICATION",
      permission_key: Permissions.MANAGE_NOTIFICATION,
      permission_module_id: 25,
    },
    {
      id: 102,
      name: "VIEW_ALL_NOTIFICATION_TEMPLATE",
      name_en: "VIEW_ALL_NOTIFICATION_TEMPLATE",
      permission_key: Permissions.VIEW_ALL_NOTIFICATION_TEMPLATE,
      permission_module_id: 25,
    },
    {
      id: 103,
      name: "VIEW_ALL_OFFICE_JURISDICTION",
      name_en: "VIEW_ALL_OFFICE_JURISDICTION",
      permission_key: Permissions.VIEW_ALL_OFFICE_JURISDICTION,
      permission_module_id: 26,
    },
    {
      id: 104,
      name: "CREATE_OFFICE_JURISDICTION",
      name_en: "CREATE_OFFICE_JURISDICTION",
      permission_key: Permissions.CREATE_OFFICE_JURISDICTION,
      permission_module_id: 26,
    },
  ];

  async run(dataSource: DataSource): Promise<any> {
    await dataSource.query("SET FOREIGN_KEY_CHECKS=0");
    await dataSource.getRepository(PermissionEntity).clear();
    await dataSource.manager.save(PermissionEntity, this.data);
    await dataSource.query("SET FOREIGN_KEY_CHECKS=1");
  }
}
