import { BaseOfficeOrganogramEntity } from "@lams/shared/database/entities/office/base-office-organogram.entity";
import { DataSource } from "typeorm";

export class BaseOfficeOrganogramSeeder {
  data: any[] = [
    {
      id: 1,
      name: "ভূমি মন্ত্রণালয়",
      name_en: "Land Ministry",
      short_name: "land",
      short_name_en: "land",
      layer_id: 1,
      is_head: 0,
      sort_order: 1,
      base_office_id: 1,
      organogram_type: 1,
      parent_id: null,
      permission_group_id: 12,
      row_status: 1,
    },
    {
      id: 2,
      name: "মন্ত্রিপরিষদ বিভাগ",
      name_en: "Cabinet Division",
      short_name: "cabinet",
      short_name_en: "cabinet",
      layer_id: 1,
      is_head: 0,
      sort_order: 1,
      base_office_id: 2,
      organogram_type: 1,
      parent_id: null,
      permission_group_id: null,
      row_status: 1,
    },
    {
      id: 3,
      name: "ভূমি সংস্কার বোর্ড",
      name_en: "ভূমি সংস্কার বোর্ড",
      short_name: "LRB",
      short_name_en: "LRB",
      layer_id: 3,
      is_head: 0,
      sort_order: 1,
      base_office_id: 3,
      organogram_type: 1,
      parent_id: 1,
      permission_group_id: null,
      row_status: 1,
    },
    {
      id: 4,
      name: "বিভাগীয় কমিশনারের কার্যালয়",
      name_en: "Divisional Commissioner's Office",
      short_name: "div com office",
      short_name_en: "div com office",
      layer_id: 6,
      is_head: 0,
      sort_order: 1,
      base_office_id: 4,
      organogram_type: 1,
      parent_id: 2,
      permission_group_id: 6,
      row_status: 1,
    },
    {
      id: 5,
      name: "জেলা প্রশাসকের কার্যালয়",
      name_en: "Deputy Commissioner's Office",
      short_name: "dc office",
      short_name_en: "dc office",
      layer_id: 8,
      is_head: 0,
      sort_order: 1,
      base_office_id: 5,
      organogram_type: 1,
      parent_id: 4,
      permission_group_id: 8,
      row_status: 1,
    },
    {
      id: 6,
      name: "উপজেলা ভূমি অফিস",
      name_en: "Upazila Land Office",
      short_name: "ULO",
      short_name_en: "ULO",
      layer_id: 9,
      is_head: 0,
      sort_order: 1,
      base_office_id: 6,
      organogram_type: 1,
      parent_id: 3,
      permission_group_id: 10,
      row_status: 1,
    },
    {
      id: 7,
      name: "বিভাগীয় কমিশনার",
      name_en: "Divisional Commissioner",
      short_name: "DIV COM",
      short_name_en: "DIV COM",
      layer_id: 6,
      is_head: 1,
      sort_order: 2,
      base_office_id: 4,
      organogram_type: 3,
      parent_id: 4,
      permission_group_id: 7,
      row_status: 1,
    },
    {
      id: 8,
      name: "জেলা প্রশাসক",
      name_en: "Deputy Commissioner",
      short_name: "DC",
      short_name_en: "DC",
      layer_id: 8,
      is_head: 1,
      sort_order: 2,
      base_office_id: 5,
      organogram_type: 3,
      parent_id: 5,
      permission_group_id: 9,
      row_status: 1,
    },
    {
      id: 9,
      name: "সহকারী কমিশনার (ভূমি)",
      name_en: "Assistant Commissioner (Land)",
      short_name: "ACLAND",
      short_name_en: "ACLAND",
      layer_id: 9,
      is_head: 1,
      sort_order: 2,
      base_office_id: 6,
      organogram_type: 3,
      parent_id: 6,
      permission_group_id: 11,
      row_status: 1,
    },
    {
      id: 10,
      name: "মাননীয় মন্ত্রী",
      name_en: "Honorable Minister",
      short_name: "minister",
      short_name_en: "minister",
      base_office_id: 1,
      organogram_type: 3,
      parent_id: 1,
      layer_id: 1,
      is_head: 1,
      sort_order: 2,
      permission_group_id: 1,
      created_by: 1,
      deleted_at: null,
      row_status: 1,
    },
  ];

  async run(dataSource: DataSource): Promise<any> {
    await dataSource.query("SET FOREIGN_KEY_CHECKS=0");
    await dataSource.getRepository(BaseOfficeOrganogramEntity).clear();
    await dataSource.manager.save(BaseOfficeOrganogramEntity, this.data);
    await dataSource.query("SET FOREIGN_KEY_CHECKS=1");
  }
}
