import { OfficeOrganogramEntity } from "@lams/shared/database/entities/office/office-organogram.entity";
import { DataSource } from "typeorm";

export class OfficeOrganogramSeeder {
  data: any[] = [
    {
      id: 1,
      name: "ভূমি মন্ত্রণালয়",
      name_en: "Land Ministry",
      sort_order: 1,
      is_head: 0,
      office_id: 1,
      user_id: null,
      base_office_organogram_id: 1,
      organogram_type: 1,
      parent_id: null,
      permission_group_id: 12,
      office_permission_group_id: null,
      idp_desk_id: null,
      login_id: null,
      row_status: 1,
    },
    {
      id: 2,
      name: "মন্ত্রিপরিষদ বিভাগ",
      name_en: "Cabinet Division",
      sort_order: 1,
      is_head: 0,
      office_id: 2,
      user_id: null,
      base_office_organogram_id: 2,
      organogram_type: 1,
      parent_id: null,
      permission_group_id: null,
      office_permission_group_id: null,
      idp_desk_id: null,
      login_id: null,
      row_status: 1,
    },
    {
      id: 3,
      name: "ভূমি সংস্কার বোর্ড",
      name_en: "ভূমি সংস্কার বোর্ড",
      sort_order: 1,
      is_head: 0,
      office_id: 3,
      user_id: null,
      base_office_organogram_id: 3,
      organogram_type: 1,
      parent_id: 1,
      permission_group_id: null,
      office_permission_group_id: null,
      idp_desk_id: null,
      login_id: null,
      row_status: 1,
    },
    {
      id: 4,
      name: "বিভাগীয় কমিশনারের কার্যালয়, ঢাকা",
      name_en: "Divisional Commissioner's Office, Dhaka",
      sort_order: 1,
      is_head: 0,
      office_id: 4,
      user_id: null,
      base_office_organogram_id: 4,
      organogram_type: 1,
      parent_id: 2,
      permission_group_id: 6,
      office_permission_group_id: null,
      idp_desk_id: null,
      login_id: null,
      row_status: 1,
    },
    {
      id: 5,
      name: "জেলা প্রশাসকের কার্যালয়, ঢাকা",
      name_en: "Deputy Commissioner's Office, Dhaka",
      sort_order: 1,
      is_head: 0,
      office_id: 5,
      user_id: null,
      base_office_organogram_id: 5,
      organogram_type: 1,
      parent_id: 4,
      permission_group_id: 8,
      office_permission_group_id: null,
      idp_desk_id: null,
      login_id: null,
      row_status: 1,
    },
    {
      id: 6,
      name: "উপজেলা ভূমি অফিস, দোহার",
      name_en: "Upazila Land Office, Dohar",
      sort_order: 1,
      is_head: 0,
      office_id: 6,
      user_id: null,
      base_office_organogram_id: 6,
      organogram_type: 1,
      parent_id: 3,
      permission_group_id: 10,
      office_permission_group_id: null,
      idp_desk_id: null,
      login_id: null,
      row_status: 1,
    },
    {
      id: 7,
      name: "বিভাগীয় কমিশনার",
      name_en: "Divisional Commissioner",
      sort_order: 2,
      is_head: 1,
      office_id: 4,
      user_id: 3,
      base_office_organogram_id: 7,
      organogram_type: 3,
      parent_id: 4,
      permission_group_id: 7,
      office_permission_group_id: null,
      idp_desk_id: "02cfde82-b20e-4b89-a14c-737ae1998638",
      login_id: "divcom_dhaka",
      row_status: 1,
    },
    {
      id: 8,
      name: "জেলা প্রশাসক",
      name_en: "Deputy Commissioner",
      sort_order: 2,
      is_head: 1,
      office_id: 5,
      user_id: 4,
      base_office_organogram_id: 8,
      organogram_type: 3,
      parent_id: 5,
      permission_group_id: 9,
      office_permission_group_id: null,
      idp_desk_id: "a15a2705-c393-4aca-a252-f83a93ebb9da",
      login_id: "dc_gazipur",
      row_status: 1,
    },
    {
      id: 9,
      name: "সহকারী কমিশনার (ভূমি)",
      name_en: "Assistant Commissioner (Land)",
      sort_order: 2,
      is_head: 1,
      office_id: 6,
      user_id: 5,
      base_office_organogram_id: 9,
      organogram_type: 3,
      parent_id: 6,
      permission_group_id: 11,
      office_permission_group_id: null,
      idp_desk_id: "c7060c22-3294-4ba5-93b0-8cc9516e1e8e",
      login_id: "acland_dhaka_sreepur",
      row_status: 1,
    },
    {
      id: 10,
      name: "মাননীয় মন্ত্রী",
      name_en: "Honorable Minister",
      sort_order: 2,
      is_head: 1,
      office_id: 1,
      user_id: 6,
      base_office_organogram_id: 10,
      organogram_type: 3,
      parent_id: 1,
      permission_group_id: 1,
      office_permission_group_id: null,
      idp_desk_id: "5015a92c-3008-4ce6-b866-8d4400ba56e0",
      login_id: "minister_land",
      row_status: 1,
    },
  ];

  async run(dataSource: DataSource): Promise<any> {
    await dataSource.query("SET FOREIGN_KEY_CHECKS=0");
    await dataSource.getRepository(OfficeOrganogramEntity).clear();
    await dataSource.manager.save(OfficeOrganogramEntity, this.data);
    await dataSource.query("SET FOREIGN_KEY_CHECKS=1");
  }
}
