import { OfficeEntity } from "@lams/shared/database/entities/office/office.entity";
import { DataSource } from "typeorm";

export class OfficeSeeder {
  data: any[] = [
    {
      id: 1,
      name: "ভূমি মন্ত্রণালয়",
      name_en: "Land Ministry",
      short_name: "land",
      short_name_en: "land",
      code: "OFFICE6408116",
      website_url: "land.gov.bd",
      base_office_id: 1,
      parent_id: null,
      layer_id: 1,
      ministry_office_id: 1,
      divisional_office_id: null,
      directorate_office_id: null,
      project_office_id: null,
      division_id: null,
      zone_id: null,
      district_id: null,
      upazila_id: null,
      circle_id: null,
      thana_id: null,
      union_id: null,
      row_status: 1,
    },
    {
      id: 2,
      name: "মন্ত্রিপরিষদ বিভাগ",
      name_en: "Cabinet Division",
      short_name: "cabinet",
      short_name_en: "cabinet",
      code: "OFFICE3778582",
      website_url: "",
      base_office_id: 2,
      parent_id: null,
      layer_id: 1,
      ministry_office_id: 2,
      divisional_office_id: null,
      directorate_office_id: null,
      project_office_id: null,
      division_id: null,
      zone_id: null,
      district_id: null,
      upazila_id: null,
      circle_id: null,
      thana_id: null,
      union_id: null,
      row_status: 1,
    },
    {
      id: 3,
      name: "ভূমি সংস্কার বোর্ড",
      name_en: "Land Reform Board",
      short_name: "LRB",
      short_name_en: "LRB",
      code: "OFFICE8308190",
      website_url: "https://www.lrb.gov.bd/",
      base_office_id: 3,
      parent_id: 1,
      layer_id: 3,
      ministry_office_id: 1,
      divisional_office_id: null,
      directorate_office_id: 3,
      project_office_id: null,
      division_id: null,
      zone_id: null,
      district_id: null,
      upazila_id: null,
      circle_id: null,
      thana_id: null,
      union_id: null,
      row_status: 1,
    },
    {
      id: 4,
      name: "বিভাগীয় কমিশনারের কার্যালয়, ঢাকা",
      name_en: "Divisional Commissioner's Office, Dhaka",
      short_name: "div com dhaka",
      short_name_en: "div com dhaka",
      code: "OFFICE3665351",
      website_url: "www.dhakadiv.gov.bd",
      base_office_id: 4,
      parent_id: 2,
      layer_id: 6,
      ministry_office_id: 2,
      divisional_office_id: null,
      directorate_office_id: null,
      project_office_id: null,
      division_id: 3,
      zone_id: null,
      district_id: null,
      upazila_id: null,
      circle_id: null,
      thana_id: null,
      union_id: null,
      row_status: 1,
    },
    {
      id: 5,
      name: "জেলা প্রশাসকের কার্যালয়, গাজীপুর",
      name_en: "Deputy Commissioner's Office, Gazipur",
      short_name: "dc office Gazipur",
      short_name_en: "dc office Gazipur",
      code: "OFFICE8782515",
      website_url: "www.gazipur.gov.bd",
      base_office_id: 5,
      parent_id: 4,
      layer_id: 8,
      ministry_office_id: 2,
      divisional_office_id: null,
      directorate_office_id: null,
      project_office_id: null,
      division_id: 3,
      zone_id: null,
      district_id: 20,
      upazila_id: null,
      circle_id: null,
      thana_id: null,
      union_id: null,
      row_status: 1,
    },
    {
      id: 6,
      name: "উপজেলা ভূমি অফিস, শ্রীপুর",
      name_en: "Upazila Land Office, Sreepur",
      short_name: "ULO",
      short_name_en: "ULO",
      code: "OFFICE6074862",
      website_url: "www.sreepur.gazipur.gov.bd",
      base_office_id: 6,
      parent_id: 3,
      layer_id: 9,
      ministry_office_id: 1,
      divisional_office_id: null,
      directorate_office_id: null,
      project_office_id: null,
      division_id: 3,
      zone_id: null,
      district_id: 20,
      upazila_id: 156,
      circle_id: null,
      thana_id: null,
      union_id: null,
      row_status: 1,
    },
  ];

  async run(dataSource: DataSource): Promise<any> {
    await dataSource.query("SET FOREIGN_KEY_CHECKS=0");
    await dataSource.getRepository(OfficeEntity).clear();
    await dataSource.manager.save(OfficeEntity, this.data);
    await dataSource.query("SET FOREIGN_KEY_CHECKS=1");
  }
}
